language: generic

cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal

# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
env:
 - GHCVER=7.8.3
 - GHCVER=7.10.1
 - GHCVER=8.0.1
 - GHCVER=8.2.2
 - GHCVER=8.4.4
 - GHCVER=8.6.2
 - GHCVER=head  # see section about GHC HEAD snapshots
 - WINDOWS=yes
 - STACK=default
 - STACK=lts-12
 - STACK=nightly

matrix:
  allow_failures:
   - env: GHCVER=8.6.2
   - env: GHCVER=head
   - env: STACK=nightly

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - mkdir -p ~/.local/bin
 - export PATH=~/.local/bin:$PATH
 # install stack
 - 'test -z "$STACK" || { curl -sSL https://get.haskellstack.org/ | sh; }'

 # stack solver needs cabal :-(
 - test -z "$STACK" -o "$STACK" = default || sudo add-apt-repository -y ppa:hvr/ghc
 - test -z "$STACK" -o "$STACK" = default || travis_retry sudo bash -c "apt-get update; apt-get install cabal-install-1.24"
 - test -z "$STACK" -o "$STACK" = default || export PATH=/opt/cabal/1.24/bin:$PATH


 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/2.4/bin:$PATH
 - export WINEPATH='C:\Program Files (x86)\GnuWin32\bin'

 - if [ "$WINDOWS" = yes ]; then export W=wine; else export W=""; fi
 - test -z "$WINDOWS"  || bash ./.travis-setup-windows.sh
 - test -z "$GHCVER" || bash ./.travis-setup-linux.sh

 - test -z "$STACK" || travis_retry sudo apt-get install g++ gcc libc6-dev libffi-dev libgmp-dev make xz-utils zlib1g-dev libwww-perl
 - 'test -z "$STACK" -o "$STACK" = default || echo "resolver: $(HEAD -S https://www.stackage.org/$STACK|grep HEAD|tail -n1|cut -d/ -f4)" > stack.yaml'
 - 'test -z "$STACK" -o "$STACK" = default || stack solver --update-config'
 - test -z "$STACK" || cat stack.yaml
 - test -z "$STACK" || stack setup


install:
 # - test -z "$STACK" || travis_retry stack solver --update-config
 - test -z "$STACK" || stack build --only-dependencies

script:
 - test -z "$GHCVER" || $W cabal new-build
 #- test -z "$GHCVER" -a -z "$WINDOWS" || $W cabal new-test
 - test -z "$GHCVER" || $W cabal check
 - test -z "$GHCVER" || $W cabal new-sdist

 - test -z "$WINDOWS" || $W cabal build

 - test -z "$STACK" || stack build --test

# The following scriptlet checks that the resulting source distribution can be built & installed
 - test -z "$GHCVER" || {
   export SRC_TGZ=$($W cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist-newstyle/sdist/;
   if [ -f "$SRC_TGZ" ]; then
      $W cabal install "./$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi;
   }
